// <auto-generated />
using System;
using ApiEstatisticasCrimes.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiEstatisticasCrimes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240309010510_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApiEstatisticasCrimes.Models.Assalto", b =>
                {
                    b.Property<int>("AssaltoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssaltoId"));

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeAgressores")
                        .HasColumnType("int");

                    b.HasKey("AssaltoId");

                    b.HasIndex("OcorrenciaId")
                        .IsUnique();

                    b.ToTable("Assaltos");
                });

            modelBuilder.Entity("ApiEstatisticasCrimes.Models.Ocorrencia", b =>
                {
                    b.Property<int>("OcorrenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OcorrenciaId"));

                    b.Property<bool>("CadastrouBoletimOcorrencia")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoOcorrencia")
                        .HasColumnType("int");

                    b.HasKey("OcorrenciaId");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("ApiEstatisticasCrimes.Models.Assalto", b =>
                {
                    b.HasOne("ApiEstatisticasCrimes.Models.Ocorrencia", "Ocorrencia")
                        .WithOne("Assalto")
                        .HasForeignKey("ApiEstatisticasCrimes.Models.Assalto", "OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ocorrencia");
                });

            modelBuilder.Entity("ApiEstatisticasCrimes.Models.Ocorrencia", b =>
                {
                    b.Navigation("Assalto");
                });
#pragma warning restore 612, 618
        }
    }
}
